name: Mostrar Hola mundo!

on: 
 workflow_call:
  inputs:
    config-path:
      required: true
      type: string
  secrets:
      token:
       required: true

jobs:
 mostrarHola:
  runs-on: ubuntu-latest
  env:
   MY_SECRET: ${{ secrets.envSEC }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Mostrar Hola, mundo!
      run: echo $MY_SECRET
